name: Python
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - name: Self test
        id: selftest
        uses: kok-xiong/test-actions@master
        with:
          bitlyToken: ${{ secrets.BITLY_TOKEN }}
          longURL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}

      - name: Telegram Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: The ${{ github.event_name }} event triggered. URL - ${{ steps.selftest.outputs.shortURL }} / https://github.com/${{ github.repository }}/commit/${{ github.sha }}.